### ISSUE TITLE
How it works

### ISSUE THREAD

**Issue by Shuhrat-java** [arrian/android-smb#1]
Did not understand how it works. Could you give some working example? App is crashing when I tried to run. It gives an error: 
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.alfresco.jlan.smb.server.CIFSConfigSection.getServerName()' on a null object reference
            at org.alfresco.jlan.smb.server.SMBServer.getServerName(SMBServer.java:319)
            at org.alfresco.jlan.smb.server.SMBServer.closeDevices(SMBServer.java:256)
            at org.alfresco.jlan.smb.server.SMBServer.run(SMBServer.java:567)
            at java.lang.Thread.run(Thread.java:818)

**Comment by sukuias12** [comment]
I hava met the same problems, anyone can answer it ?

**Comment by LIUTAOGE** [comment]
obvious it is wrong because of the code is not complete. your can visit "android-smb-client-server" in github, but I only can access the smburl in mac without window that I think window need only port in 445.
but I cant try run in 445 with port because my phone not root .if you try root phone success in window ,please tell me in here,thank you

**Comment by LIUTAOGE** [comment]
sorry ,search  "Android-Samba-Server-Clinet" in github.   not "android-smb-client-server"

**Comment by huanyuan** [comment]
must root?

**Comment by huanyuan** [comment]
devices must root？
